sudo: required
services:
  - docker

before_install:
  - docker build -t ahmedkhaledre/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run ahmedkhaledre/react-test npm run test -- --coverage

after_success:
  - docker build -t ahmedkhaledre/multi-client ./client
  - docker build -t ahmedkhaledre/multi-nginx ./nginx
  - docker build -t ahmedkhaledre/multi-server ./server
  - docker build -t ahmedkhaledre/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images
  - docker push ahmedkhaledre/multi-nginx
  - docker push ahmedkhaledre/multi-client
  - docker push ahmedkhaledre/multi-server
  - docker push ahmedkhaledre/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-677505090583
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY